// Code generated by protoc-gen-go-scaffold. DO NOT EDIT.

package handler

import (
	"context"
	appError "github.com/harryosmar/protobuf-go/error"
	pb "github.com/harryosmar/protobuf-go/gen/user"
	"github.com/harryosmar/protobuf-go/logger"
	"github.com/harryosmar/protobuf-go/usecase"
)

type HelloServiceHandler interface {
	GetHello(context.Context, *pb.HelloRequest) (*pb.HelloResponse, error)
}

type helloServiceHandler struct {
	pb.UnimplementedUserServiceServer
	usecase usecase.HelloServiceUsecase
}

func NewHelloServiceHandler(usecase usecase.HelloServiceUsecase) HelloServiceHandler {
	return &helloServiceHandler{usecase: usecase}
}

func (u *helloServiceHandler) GetHello(ctx context.Context, req *pb.HelloRequest) (*pb.HelloResponse, error) {
	var (
		err error
		log = logger.FromContext(ctx)
	)
	log.Info("helloServiceHandler.GetHello called")

	defer func() {
		if err != nil {
			log.Error(err.Error())
		}
	}()

	if err = req.Validate(); err != nil {
		return nil, appError.ErrInvalidArgument.WithMessage("validation failed: %v", err)
	}

	return u.usecase.GetHello(ctx, req)
}
