// Code generated by protoc-gen-go-scaffold. DO NOT EDIT.

package handler

import (
	"context"
	appError "github.com/harryosmar/protobuf-go/error"
	pb "github.com/harryosmar/protobuf-go/gen/user"
	"github.com/harryosmar/protobuf-go/logger"
	"github.com/harryosmar/protobuf-go/usecase"
)

type UserServiceHandler interface {
	CreateUser(context.Context, *pb.CreateUserRequestDTO) (*pb.CreateUserResponseDTO, error)
	GetUser(context.Context, *pb.GetUserRequestDTO) (*pb.GetUserResponse, error)
	DeleteUser(context.Context, *pb.DeleteUserRequestDTO) (*pb.DeleteUserResponseDTO, error)
	UpdateUser(context.Context, *pb.UpdateUserRequestDTO) (*pb.UpdateUserResponseDTO, error)
	ListUsers(context.Context, *pb.ListUsersRequestDTO) (*pb.ListUsersResponseDTO, error)
}

type userServiceHandler struct {
	pb.UnimplementedUserServiceServer
	usecase usecase.UserServiceUsecase
}

func NewUserServiceHandler(usecase usecase.UserServiceUsecase) UserServiceHandler {
	return &userServiceHandler{usecase: usecase}
}

func (u *userServiceHandler) CreateUser(ctx context.Context, req *pb.CreateUserRequestDTO) (*pb.CreateUserResponseDTO, error) {
	var (
		err error
		log = logger.FromContext(ctx)
	)
	log.Info("userServiceHandler.CreateUser called")

	defer func() {
		if err != nil {
			log.Error(err.Error())
		}
	}()

	if err = req.Validate(); err != nil {
		return nil, appError.ErrInvalidArgument.WithMessage("validation failed: %v", err)
	}

	return u.usecase.CreateUser(ctx, req)
}

func (u *userServiceHandler) GetUser(ctx context.Context, req *pb.GetUserRequestDTO) (*pb.GetUserResponse, error) {
	var (
		err error
		log = logger.FromContext(ctx)
	)
	log.Info("userServiceHandler.GetUser called")

	defer func() {
		if err != nil {
			log.Error(err.Error())
		}
	}()

	if err = req.Validate(); err != nil {
		return nil, appError.ErrInvalidArgument.WithMessage("validation failed: %v", err)
	}

	return u.usecase.GetUser(ctx, req)
}

func (u *userServiceHandler) DeleteUser(ctx context.Context, req *pb.DeleteUserRequestDTO) (*pb.DeleteUserResponseDTO, error) {
	var (
		err error
		log = logger.FromContext(ctx)
	)
	log.Info("userServiceHandler.DeleteUser called")

	defer func() {
		if err != nil {
			log.Error(err.Error())
		}
	}()

	if err = req.Validate(); err != nil {
		return nil, appError.ErrInvalidArgument.WithMessage("validation failed: %v", err)
	}

	return u.usecase.DeleteUser(ctx, req)
}

func (u *userServiceHandler) UpdateUser(ctx context.Context, req *pb.UpdateUserRequestDTO) (*pb.UpdateUserResponseDTO, error) {
	var (
		err error
		log = logger.FromContext(ctx)
	)
	log.Info("userServiceHandler.UpdateUser called")

	defer func() {
		if err != nil {
			log.Error(err.Error())
		}
	}()

	if err = req.Validate(); err != nil {
		return nil, appError.ErrInvalidArgument.WithMessage("validation failed: %v", err)
	}

	return u.usecase.UpdateUser(ctx, req)
}

func (u *userServiceHandler) ListUsers(ctx context.Context, req *pb.ListUsersRequestDTO) (*pb.ListUsersResponseDTO, error) {
	var (
		err error
		log = logger.FromContext(ctx)
	)
	log.Info("userServiceHandler.ListUsers called")

	defer func() {
		if err != nil {
			log.Error(err.Error())
		}
	}()

	if err = req.Validate(); err != nil {
		return nil, appError.ErrInvalidArgument.WithMessage("validation failed: %v", err)
	}

	return u.usecase.ListUsers(ctx, req)
}
